spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/memento
    username: memento
    password: memento

app:
  batch-size: 2
  timeout-seconds: 1
  bot-token: ${BOT_TOKEN}
  max-submit-attempts: 2
  receiver-chat-id: 391468704
  sender-chat-id: 418177113
  task-executor:
    max-pool-size: 3
    queue-capacity: 3
    keep-alive-seconds: 30
