spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/memento}
    username: ${DB_USER:memento}
    password: ${DB_PASS:memento}

app:
  batch-size: 1
  timeout-seconds: 30
  bot-token: ${BOT_TOKEN}
  max-submit-attempts: 2
  min-remind-frequency-minutes: 30
  receiver-chat-id: ${RECEIVER_CHAT_ID}
  sender-chat-id: ${SENDER_CHAT_ID}
  task-executor:
    max-pool-size: 3
    queue-capacity: 3
    keep-alive-seconds: 30
