spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/memento
    username: memento
    password: memento

app:
  task-executor:
    max-pool-size: 10
    queue-capacity: 20
    keep-alive-seconds: 30
